"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[username]
show_always = false
format = "[$user](green)"

[hostname]
ssh_only = true
format = "[@$hostname](green) "

[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = false

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch](242)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red) ($ahead_behind$stashed)](white) "
conflicted = "\u200C"
untracked = "\u200C"
modified = "\u200C"
staged = "\u200C"
renamed = "\u200C"
deleted = "\u200C"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)](yellow)\) '

[cmd_duration]
format = "[$duration](yellow) "

[python]
format = "[$virtualenv](242) "
detect_extensions = []
detect_files = []
