echo '[[ -f ~/.bashrc ]] && source ~/.bashrc' >> ~/.bash_profile
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc
